version: "3.8"

services:
  frontend:
    build: .
    ports:
      - "3001:80"
    environment:
      - REACT_APP_BACKEND_URL=http://localhost:5000
      - REACT_APP_PORT=3001
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
